apiVersion: apps/v1
kind: Deployment
metadata:
  name: sujiths-Deployment
spec:
  replicas: 2
  selector:
    matchLables:
      app: harshith
  template:
    metadata:
      labels:
        app: harshith
    spec:
      containers:
        - name: sujitha-cont
          image: harshithreddy628/sujitha:latest
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: sujitha-svc 
spec:
  type: LoadBalancer
  selector:
    app: harshith
  ports:
    - port: 3001
      targetPort: 3000
